# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-12 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180412_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
