# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-13 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180412_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='../static/images/FoundationValrico.jpg', upload_to='static/images/'),
            preserve_default=False,
        ),
    ]
