# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-14 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='static/images/static/images'),
        ),
    ]
