# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-26 12:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180325_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 26, 12, 31, 31, 85677, tzinfo=utc)),
        ),
    ]
